" Most important thing!!
set nocompatible

"=== Source ==="
source ~/.vim/keymaps.vim           " For keymapping
source ~/.vim/vim-plug.vim          " List of plugins

"=== Appearance ==="
set noshowmode                    " Replace by vim-airline
set laststatus=2
set shortmess+=I                  " Disable Vim startup messages
set nowrap
set cursorline
set number relativenumber
set splitbelow splitright         " Split window below/right
set scrolloff=5                   " At least left 5 line
set wildmenu                      " Enable auto completion menu in command mode
set updatetime=300
set completeopt=menu,menuone,noinsert

"=== Themes ==="
syntax enable
set t_Co=256
set termguicolors
try
    set background=dark
    colorscheme solarized8_flat
catch
    echohl WarningMsg | echo "You don't have the solarized8 theme!" | echohl None
endtry
" For transparent
hi Normal guibg=NONE ctermbg=NONE
hi SpecialKey guibg=NONE
hi VertSplit guibg=NONE ctermbg=NONE

"=== Tab/Indent ==="
set tabstop=4       " number of visual space per TAB
set softtabstop=4   " number of spaces in tab when editing
set shiftwidth=4    " number of spaces to use for autoindent
set expandtab       " expand tab to spaces so that tabs are spaces
set smarttab
set autoindent
set smartindent

"=== Search/Highlight ==="
set ignorecase smartcase
set incsearch
set hlsearch

"=== Variables ==="
" let g:loaded_netrwPlugin = 1
let g:loaded_2html_plugin =1

"=== Undercurl ==="
let &t_Cs = "\e[4:3m"
let &t_Ce = "\e[4:0m"
highlight SpellBad cterm=undercurl ctermfg=red ctermbg=NONE gui=undercurl guifg=red guibg=NONE

"=== Other ==="
filetype plugin indent on
set viminfofile=$XDG_STATE_HOME/vim/viminfo
set history=200
set noswapfile
set nobackup
set modelines=0
set nomodeline
set autoread
set confirm
set clipboard^=unnamed,unnamedplus
set backspace=eol,start,indent          " Make Backspace behave normally
set encoding=utf-8
set spelllang=en,cjk
set magic                               " For regular expression
set regexpengine=0                      " Set regular expression engine automatically
set wildignore+=*.log,*/node_modules/*
set visualbell
set noerrorbells
set t_vb=
set tm=500

"=== Autocmds ==="
" Delete trailing white space on save
autocmd BufWritePre * :%s/\s\+$//e
